### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by josephgupkim** [lucynaaleksandra/jamming#3]
It seems that your project was missing some scripts and I wasn't able to get your Jammming project running on my machine. It seems for the most part that your project looks well written so I'm confident you could get it running if all the necessary code is present.

**Comment by lucynaaleksandra** [comment]
The .env file with Spotify client_id was added: 
README has been updated: 
![image](https://user-images.githubusercontent.com/30958921/38376091-cfa72b52-38c5-11e8-8441-0c2d835dae1f.png)
This project should be running locally now. 
Thanks for feedback.
