### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [lucynaaleksandra/jamming#4]
A well written Jammming project that had a structured and organized code base.
Unfortunately was missing some crucial scripts and code to get the project running on my local machine but great attempt thus far nevertheless.

Grade: Meets expectation.

**Comment by lucynaaleksandra** [comment]
The .env file with Spotify client_id was added: 
README has been updated: 
![image](https://user-images.githubusercontent.com/30958921/38376091-cfa72b52-38c5-11e8-8441-0c2d835dae1f.png)
This project should be running locally now. 
Thanks for feedback.
